#!/usr/bin/env bash
# A Bash script that transfers a file from the client to a server

if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no "$4" "$1" "$3@$2:~/"
fi
