#!/usr/bin/env bash

# configure an Ubuntu server and change localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8.

# Configure facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Configure localhost to resolve to 127.0.0.2
echo "127.0.0.2 localhost" >> /etc/hosts